version: "3"
services:
  myapp:
    container_name: myApp
    build:
      context: ./myapp
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - ./myapp:/workspace